import type { Metadata } from "next";
import { Analytics } from'@vercel/analytics/next';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/src/common/provider/ThemeProvider";
import BottomBar from "@/src/common/components/BottomBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Li Anthony Gómez González - Portafolio",
  description: "Generated by create next app",
};

if (typeof window !== "undefined") window.global = window;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Analytics />
        <BottomBar />
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
